appearance:
  mode: system
  color: emerald

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal academic website of Xiaoyu He, PhD researcher in causal inference and machine learning.'
    same_as:
      - 'https://github.com/sereneHe'
      - 'https://www.linkedin.com/in/xiaoyu-he-b91a21160/'
      - 'https://orcid.org/0000-0003-0859-9911'
      - 'https://scholar.google.com/citations?hl=zh-CN&user=KBf4QOEAAAAJ&view_op=list_works&gmla=AEk_c1sJwlP7udLWpI4Kpl9BxiVXXVtYy2r9fnM4Y6pe0UKAP6D3UFCw7rLAN92Ug9GPErOPVs1me22ou9XCr5t83EqGmfnP6Y3j7lz3Pls'
      - 'https://cs.fel.cvut.cz/en/people/hexiaoyu'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Xiaoyu He"

footer:
  copyright:
    notice: '© {year} Xiaoyu He. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  math:
    enable: false
  privacy_pack:
    enable: false
